
import { config } from 'dotenv';
config();

import '@/ai/flows/ai-interaction-engine.ts';
import '@/ai/flows/ai-dose-calculator.ts';
import '@/ai/flows/allergy-checker.ts';
import '@/ai/flows/drug-monograph-lookup.ts';
import '@/ai/flows/prescription-reader.ts';
import '@/ai/flows/drug-food-interaction.ts';
import '@/ai/flows/lab-report-analyzer.ts';
import '@/ai/flows/adherence-reporter.ts';
import '@/ai/flows/symptom-checker.ts'
import '@/ai/flows/refill-manager.ts';
import '@/ai/tools/healthcare-finder.ts';
import '@/ai/tools/pharmacy-finder.ts';
import '@/ai/flows/diet-planner.ts';
import '@/ai/flows/lifestyle-suggester.ts';
import '@/ai/flows/nutrition-coach.ts';
import '@/ai/flows/lecture-notes-analyzer.ts';
import '@/ai/flows/e-library-search.ts';
import '@/ai/flows/herbal-knowledge-hub.ts';
import '@/ai/flows/study-material-generator.ts';
import '@/ai/flows/flashcard-generator.ts';
import '@/ai/flows/clinical-case-simulator.ts';
import '@/ai/flows/sop-generator.ts';
import '@/ai/flows/osce-station-generator.ts';
import '@/ai/flows/question-generator.ts';
import '@/ai_flows/anagram-generator.ts';
import '@/ai_flows/crossword-generator.ts';
import '@/ai_flows/word-search-generator.ts';
import '@/ai_flows/matching-game-generator.ts';
import '@/ai_flows/mnemonic-generator.ts';
import '@/ai_flows/study-planner.ts';
import '@/ai_flows/bsa-dose-calculator.ts';
import '@/ai_flows/iv-rate-calculator.ts';
import '@/ai_flows/compounding-calculator.ts';
import '@/ai_flows/reference-generator.ts';
import '@/ai/flows/drug-card-flashcard-generator.ts';
import '@/ai/flows/drug-card-quiz-generator.ts';
import '@/ai/flows/drug-card-case-mcq-generator.ts';
import '@/ai/flows/ai-assistant-helper.ts';
import '@/ai/flows/virtual-lab-simulator.ts';
import '@/ai/flows/mnemonic-generator.ts';
